name: Continuous integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      matrix:
        rust:
          - 1.75.0
          - stable
          - beta
          - nightly
        include:
          - rust: nightly
            coverage: 'send'
            components: llvm-tools

    steps:
    - uses: actions/checkout@v4

    - name: Install ${{ matrix.rust }} toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain:  ${{ matrix.rust }}
        components: ${{ matrix.components }}
        target: thumbv7em-none-eabihf
        override: true

    - name: Tests
      env:
        RUSTFLAGS: '-D warnings'
      run: |
        cargo build --verbose
        cargo test --verbose
        cargo build --verbose --no-default-features
        cargo test --verbose --no-default-features
        cargo build --verbose --no-default-features --features=alloc
        cargo test --verbose --no-default-features --features=alloc
        cargo test -r --verbose
        cargo test -r --verbose --no-default-features
        cargo test -r --verbose --no-default-features --features=alloc
        cargo build -p ser-write --verbose --features=arrayvec,heapless
        cargo test -p ser-write --verbose --features=arrayvec,heapless
        cargo build -p ser-write-json-embedded-example --target thumbv7em-none-eabihf --verbose
        cargo build -p ser-write-msgpack-embedded-example --target thumbv7em-none-eabihf --verbose
